# PRMS Parameter Generator Inputs
[MODEL_INFO]
project_folder = "/home/dgketchum/PycharmProjects/MIHMS/example/data"
project_name = "uyws_carter"
hru_cellsize = 3000

# Simulation Period yyyy/mm/dd
start_time = "2016-10-01"
end_time = "2017-12-31"

# Units: Note that MANY module-specific parameters are hard-coded.
# The units for .day files used in CBhru, for example, are hard-coded.
# SI/standard units, these must be handled explicitly in the model building code
# The below units are mostly to indicate how we introduce data in the params and data files
# 0: standard; 1: SI/metric
elev_units = 1
precip_units = 1
temp_units = 1
runoff_units = 1

selected_gage = "06192500"
# selected_stations = "USC00243378"
# selected_stations = ["USC00245080", "USC00243378"]
selected_stations = false

# prms_exe = "/media/research/IrrigationGIS/software/prms5.2.0_linux/bin/prms"
prms_exe = "/home/dgketchum/prms_5.2.1_linux/bin/prms"
gdal_warp_exe = "/home/dgketchum/miniconda3/envs/opnt/bin/gdalwarp"

[INPUT_PATHS]
#### Following paths relative to 'project_folder' above #####

# Study Area
study_area_path = "domain/carter_basin.shp"

# Model outlet point
model_outlet_path = "domain/carter_gage.shp"

usgs_gages = "gages/usgs_gages_30yr.shp"
ghcn_stations = "ghcn/ghcn_stations_pnw.shp"
snotel_stations = "snotel/snotel_stations.shp"
all_stations = "met/stations.json"

lake_path = "nhd/uyws_lakes.shp"

# Rasters
raster_folder = "rasters"
elevation = "rasters/elevation.tif"
landfire_type = "rasters/landfire_type.tif"
landfire_cover = "rasters/landfire_cover.tif"
ksat = "rasters/ksat.tif"
awc = "rasters/awc.tif"
clay = "rasters/clay.tif"
sand = "rasters/sand.tif"
loam = "rasters/loam.tif"
nlcd = "rasters/nlcd.tif"

# if stations xyz dist
prms_stations_shp = "met/selected_stations.shp"

## Remap Files
remap_folder = "remaps"

# Data file information
prms_data_ghcn = "ghcn"
prms_data_stations = "met/selected_stations.json"
prms_data_zones = "met/precip_zones.shp"
prms_data_gages = "gages/gages.json"

[MODEL_PATHS]
#### Following paths relative to 'project_folder/{project_name}_{hru_cellsize}' above #####
## PRMS Control/Data/Parameter
parameter_folder = "input"
control_folder = "control"
data_folder = "input"
output_folder = "output"
hru_folder = "hru_params"

# Data file information
prms_data_ghcn = "ghcn"
prms_data_stations = "met/selected_stations.json"
prms_data_gages = "gages/gages.json"
